name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install NPM dependdencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Build site
        run: npm run build

      - name: Copy static assets
        run: cp -r assets/audio dist/

      - name: Deploy Site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          git-config-name: "GitHub Actions"
          git-config-email: "noreply@github.com"
